services:

  tagcloud:
    image: tag
    command: -i trump0

  filter:
    image: filter
    command: Trump,trump0 -i twitter_texts -o trump0

  topic:
    image: topic_analysis
    command: 100,#,6 -i trump0

  stats:
    image: stats
    command: -i twitter_texts,reddit_comments,reddit_submissions
